#!/usr/bin/env bash

# Whois
# get whois from an url
# from: github.com/paulirish/dotfiles
#
# usage:
# whos https://www.google.de
# => whois information/

function whois() {
	local domain=$(echo "$1" | awk -F/ '{print $3}') # get domain from URL
	if [ -z $domain ] ; then
		domain=$1
	fi
	echo "Getting whois record for: $domain …"
	/usr/bin/whois -h whois.internic.net $domain | sed '/NOTICE:/q'
}